# Generated by Django 4.2.4 on 2023-08-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_emails',
            field=models.BooleanField(default=True),
        ),
    ]
