# Generated by Django 4.2.4 on 2023-08-17 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Файл')),
                ('filename', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Новый'), (1, 'Отредактированный'), (2, 'Удален')], default=0)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
