# Generated by Django 4.2.4 on 2023-08-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_status_alter_document_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codereview',
            old_name='file',
            new_name='document',
        ),
    ]
